name: CI workflow Test

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'applications/client/**'

  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'applications/client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm i

      - name: Build Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
