name: CI workflow Test

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm i
        working-directory: ./applications/client

      - name: Build Project
        run: npm run build --if-present
        working-directory: ./applications/client

      - name: Run Tests
        run: npm test
        working-directory: ./applications/client

      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
